
disabled_rules: # Rule identifiers to exclude from running
  #warning
  - cyclomatic_complexity #方法中的条件判断太多不超过10个
  - trailing_whitespace #尾部空白行（使用了的话，空行会warning）

  #有待修改
  - type_name #类型名字3-40个字之间，开头大写, 
  - legacy_constructor  #使用swift的构造器(感觉没有必要)，意思比如CGPointMake(10, 20) -> CGPoint（x: 10， y: 20）

  # 以下是我感觉没有必要修改的 
  - private_over_fileprivate
  - compiler_protocol_init #NSNumber 初始化(没有必要)
  - redundant_string_enum_value #字符串枚举变量名和值不要相等
  - unused_optional_binding # !=nil比let _ = 好（并不觉得）
  - multiple_closures_with_trailing_closure #这个会和Xcode自己的style冲突，暂时不作考虑
  - empty_enum_arguments #case .failure( _) 不太好改，和swift编译warning冲突

  - vertical_parameter_alignment  #多行变量（形参）要对齐
  - todo #提醒你去做 - low
  - fallthrough #不要用这个在switch中 用default或者别的
  - vertical_whitespace   #垂直方向上的空格行，限制为一行（注释除外）

  #error
  - identifier_name #！开头小写（太多）
  - force_cast #强制转换 as! ，这个超多，要用as?

opt_in_rules: #必须遵守的规则,其实是默认打开的，我只是列出来
  - colon #冒号和前面的变量紧挨着
  - yoda_condition
  - trailing_semicolon  #末尾去分号
  - comma  #逗号前紧靠后空格
  - opening_brace  #在声明的时候， 左大括号应该有一个空格，并且在同一行
  - trailing_comma   #尾部不加逗号， 这个属性主要针对数组和字典最后一个元素 [1,2,] -> [1, 2]
  - statement_position  #else 或者catch 应该跟在上一个陈述句后面再加个空格
  - mark  #mark前后各空一格
  - operator_whitespace #func ==() 加个空格 - 好改
  - implicit_getter #只读属性不用加get，直接return
  - switch_case_alignment #case要和switch对齐
  - unneeded_break_in_switch #switch中不必要的break
  - control_statement #if等条件判断不要有括号
  - unused_closure_parameter #回调的形参没用到,用_代替
  - file_length #文件字数
  - line_length #行字数
  - type_body_length #类的内部代码行数<200
  - function_body_length  #方法内部的行数
  - function_parameter_count #形参不要大于5个
  - for_where #用for where 不要for if XX==XX
  - weak_delegate #！delegate 用weak声明
  - large_tuple #返回的元祖最多2个元素  
  - nesting #类型嵌套至多一层
  - syntactic_sugar #使用语法糖-Array<Int> -> [Int]
  - shorthand_operator #赋值的时候不建议复杂计算，建议value /= 2 而不是value = value / 2
  - force_try #强制try?

file_length:
  warning: 650  #400
  error: 1200   #1000

line_length:
  warning: 350  #120
  error: 400    #200

type_body_length:
  warning: 300  #200
  error: 400    #350

function_body_length:
  warning: 160  #40
  error: 200    #100

function_parameter_count:
  warning: 10 #5
  error: 15   #8

large_tuple:
  warning: 5
  error: 8

nesting:
  type_level:
    warning: 5
  statement_level:
    warning: 8

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - alo7-student/Model/MachineGenerated
  - alo7-studen/Network
  - alo7-student-certificate
  - document
  - fastlane
  - Script

reporter: "xcode"